### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by fcdl94** [FocoosAI/focoos#33]
I'm trying to install on Jetson ORIN AGX.

First, I tried to install following the docs:
```bash
$ pip install 'focoos[tensorrt] @ git+https://github.com/FocoosAI/focoos.git'
Defaulting to user installation because normal site-packages is not writeable
Collecting focoos[tensorrt]@ git+https://github.com/FocoosAI/focoos.git
  Cloning https://github.com/FocoosAI/focoos.git to /tmp/pip-install-wkgsfo2n/focoos_d52bc127c10443b4ac8d3c61661de086
  Running command git clone --filter=blob:none --quiet https://github.com/FocoosAI/focoos.git /tmp/pip-install-wkgsfo2n/focoos_d52bc127c10443b4ac8d3c61661de086
  Resolved https://github.com/FocoosAI/focoos.git to commit cf70cdaacad70d21a969ea44569eceb030c8c638
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package focoos produced metadata for project name unknown. Fix your #egg=focoos fragments.
Discarding git+https://github.com/FocoosAI/focoos.git: Requested unknown from git+https://github.com/FocoosAI/focoos.git has inconsistent name: filename has 'focoos', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement focoos (unavailable) (from versions: none)
ERROR: No matching distribution found for focoos (unavailable)
```

Then I cloned the repo and tried to install by:
```bash
$ pip install '.[gpu,tensorrt]'
Defaulting to user installation because normal site-packages is not writeable
Processing /home/grosi/focoos
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
WARNING: unknown 0.0.0 does not provide the extra 'gpu'
WARNING: unknown 0.0.0 does not provide the extra 'tensorrt'
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1789 sha256=ca48a24a5ff122b281ffd49b17439a238b77e836f8ebe93196b9da6025da86a4
  Stored in directory: /tmp/pip-ephem-wheel-cache-d1g9jyp_/wheels/8f/66/73/d045004fc53f15e064a42914335a7035533779b833a9d8f567
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```
but
``` bash
$ python
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import focoos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grosi/focoos/focoos/__init__.py", line 1, in <module>
    from .focoos import Focoos
  File "/home/grosi/focoos/focoos/focoos.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
>>> import focoos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grosi/focoos/focoos/__init__.py", line 1, in <module>
    from .focoos import Focoos
  File "/home/grosi/focoos/focoos/focoos.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

``` bash
$ pip install tqdm
Defaulting to user installation because normal site-packages is not writeable
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 589.3 kB/s eta 0:00:00
Installing collected packages: tqdm
  WARNING: The script tqdm is installed in '/home/grosi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed tqdm-4.67.1
```

``` bash
$ python
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import focoos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grosi/focoos/focoos/__init__.py", line 1, in <module>
    from .focoos import Focoos
  File "/home/grosi/focoos/focoos/focoos.py", line 21, in <module>
    from focoos.config import FOCOOS_CONFIG
  File "/home/grosi/focoos/focoos/config.py", line 4, in <module>
    from pydantic_settings import BaseSettings
ModuleNotFoundError: No module named 'pydantic_settings'
```

**Comment by giuseppeambrosio97** [comment]
Check that gpu and tensorrt are not mutual exclusive.

**Comment by giuseppeambrosio97** [comment]
Change in the docs that gpu and tensorrt are not mutual exclusive 

https://focoosai.github.io/focoos/getting_started/installation/#installation-options
